# Nacos 服务注册与配置中心
# 引用 future-spring-cloud 模块后，只需简单配置即可启用服务注册
spring:
  application:
    name: future-http-file
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.3.100:8848  #${NACOS_SERVER_ADDR:192.168.3.100:8848}
        namespace: FUTURE-GROUP  #${NACOS_NAMESPACE:FUTURE-GROUP}
        group: DEFAULT_GROUP # ${NACOS_GROUP:DEFAULT_GROUP}
        prefer-ip-address: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        metadata:
          version: 1.0
          region: default
      config:
        enabled: true
        server-addr: 192.168.3.100:8848  #${NACOS_SERVER_ADDR:192.168.3.100:8848}
        namespace: FUTURE-GROUP # ${NACOS_NAMESPACE:FUTURE-GROUP}
        group: DEFAULT_GROUP #${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
        import-check:
          enabled: false
        shared-configs:
          - data-id: common.yml
            group: DEFAULT_GROUP
            refresh: true
